### ISSUE TITLE
error at: conn = Connection()

### ISSUE THREAD

**Issue by beowwulf** [tariqdaouda/pyArango#1]
I want to use your pyarango, but I cannot even get connected. Here is the error i get:

  File "pyarango-test1.py", line 8, in <module>
    conn = Connection(arangoURL='http://localhost:8529') #or with just conn = Connection()
  File "/usr/local/lib/python2.7/dist-packages/pyArango/connection.py", line 19, in __init__
    self.reload()
  File "/usr/local/lib/python2.7/dist-packages/pyArango/connection.py", line 27, in reload
    data = r.json()
TypeError: 'dict' object is not callable

I can't find any related threads on it, can somebody help me with this?

**Comment by tariqdaouda** [comment]
Hi,

I have just tried it and and it works. pyArango uses requests to communicate with ArangoDB and calling the json() function is the way you retrieve the json content. If you ever encounter the same problem please let me know.

**Comment by beowwulf** [comment]
Hey Tariq,
Yes, thank you.. I got some help on stackoverflow, the answer to do with requests-library, it was an old version:
http://stackoverflow.com/questions/28521142/typeerror-dict-object-is-not-callable-in-connecting-arangodb-python

and django/python didnt say anything about it...

**Comment by tariqdaouda** [comment]
Hey,

That's good to know, thank you for posting the answer.

Cheers,
