### ISSUE TITLE
Feature Request: python3 Support

### ISSUE THREAD

**Issue by jbcurtin** [tariqdaouda/pyArango#10]
```
Python 3.4.3
>>> import pyArango
>>> from pyArango.connection import Connection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.virtualenvs/rmusic.spider/lib/python3.4/site-packages/pyArango/connection.py", line 4, in <module>
    from database import Database, DBHandle
ImportError: No module named 'database'
```

**Comment by mikean92** [comment]
Same problem here:

```
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyArango.connection import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pyArango/connection.py", line 4, in <module>
    from database import Database, DBHandle
ImportError: No module named 'database'
```

**Comment by brennv** [comment]
This! Forking now, any advice before I get started? :)

**Comment by tariqdaouda** [comment]
Hi @brennv!
I've just created a new branch *python3* to centralize the developments.
Here are some things to pay attention to:
- Metaclasses (there's a package called six that allowd you to define metaclasses compatible with python 2 and 3)
- Compatibility with python 2

**Comment by brennv** [comment]
Thanks @tariqdaouda! Switching to the new branch. Brushing up on [six](https://pythonhosted.org/six/) now with [python-future](http://python-future.org/compatible_idioms.html).

**Comment by tariqdaouda** [comment]
Great! :)

**Comment by brennv** [comment]
Added travis so we can watch builds pass or fail in py2 and py3 at the same time https://github.com/tariqdaouda/pyArango/pull/24

**Comment by brennv** [comment]
Making progress, currently tripping on transactions and creation errors
https://travis-ci.org/brennv/pyArango/builds/145276425

**Comment by tariqdaouda** [comment]
The tests on [python3](https://github.com/tariqdaouda/pyArango/tree/python3) run without problem or warnings on my machine on python 3.4. Guess all we have left is to make it compatible with 2.7 again.

**Comment by brennv** [comment]
Agreed. Could we get #28 and #30 merged into the python3 branch?

**Comment by tariqdaouda** [comment]
Hi Guys, 

I've performed a little python-future magic. The last I've just pushed on [python3](https://github.com/tariqdaouda/pyArango/tree/python3) should support both python 3 and python 2.

Can you confirm that?

**Comment by brennv** [comment]
Nice! Looks good, it's time for some schwag #31

**Comment by tariqdaouda** [comment]
Ok guys! I've merge all your pull requests. I'm closing this issue now, both pythons a finally supported. Thanks for your help!
