### ISSUE TITLE
Handle 404 (cursor not found) during batch processing

### ISSUE THREAD

**Issue by komal-SkyNET** [tariqdaouda/pyArango#108]
Once the client goes into batch processing mode, it always looks for the "result" attribute in the HTTP response without checking if it's a valid HTTP response in the first place. In scenarios when the cursor has expired at the DB end; the client doesn't learn/react to this (rather keeps looking for "result" attribute in all HTTP responses).

I can make the change and submit a pull request upon confirmation; please let me know.

**Comment by komal-SkyNET** [comment]
Submitted pull request.

Handle cursor 404 during batch processing #109
 Open	komal-SkyNET wants to merge 1 commit into tariqdaouda:master from komal-SkyNET:master

**Comment by tariqdaouda** [comment]
Merged
