### ISSUE TITLE
Have better defaults in the Database.AQLQuery method

### ISSUE THREAD

**Issue by cabalamat** [tariqdaouda/pyArango#12]
When I attempt to run the code:

    queryResult = db.AQLQuery(aql, rawResults=True)

I get the error message: "pyArango.theExceptions.QueryError: expecting non-zero value for <batchSize>". To fix this I have to instead say something like:

    queryResult = db.AQLQuery(aql, rawResults=True, batchSize=100)

I think the API would look nicer if `batchSize` had a usable default.

**Comment by tariqdaouda** [comment]
Done, actually it was a bug, the default value was 0. Thanks for bringing that up!
