### ISSUE TITLE
docs are broken

### ISSUE THREAD

**Issue by patrickboland4** [tariqdaouda/pyArango#124]
![image](https://user-images.githubusercontent.com/5661219/47044773-b6426f80-d156-11e8-803d-130d180ae60e.png)

Kindly note the docs are broken - see 
https://pyarango.readthedocs.io/en/stable/database.html

**Comment by jayrbolton** [comment]
Docs are still broken. Would you like help with maintenance on this project?

**Comment by tariqdaouda** [comment]
Fixed.

**Comment by Darkheir** [comment]
I'm still not able to see the documentation...

**Comment by backwardspy** [comment]
@tariqdaouda Every page except the index appears to be empty.
![image](https://user-images.githubusercontent.com/289746/57786856-2daba200-772c-11e9-9166-ba1945f69860.png)

**Comment by tariqdaouda** [comment]
Hi,

This is a problem with 'stable' version and I could not figure out what's the reason behind it. The [latest](https://pyarango.readthedocs.io/en/latest) version is however ok.

Cheers,

**Comment by backwardspy** [comment]
Ah, that's perfect. Thanks for your prompt response!
