### ISSUE TITLE
KeyError: 'collections'

### ISSUE THREAD

**Issue by koorukuroo** [tariqdaouda/pyArango#16]
I received following error with ArangoDB 3.0.0 [linux] 64bit

`from pyArango.connection import *`
`conn = Connection(arangoURL='http://root:password@localhost:8529')`
`conn.createDatabase(name = "test")`

/lib/python2.7/site-packages/pyArango/database.pyc in reloadCollections(self)
     37                         self.collections = {}
     38 
---> 39                         for colData in data["collections"] :
     40                                 colName = colData['name']
     41                                 if colData['isSystem'] :

KeyError: 'collections'

Maybe 'collections' have removed in ver3..?

**Comment by tariqdaouda** [comment]
Hi,

Could you give me the whole traceback?

**Comment by koorukuroo** [comment]
Hi!
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-d5ff58bd0bf3> in <module>()
----> 1 db = conn.createDatabase(name = "test10")

/home/user/git/pyArango/pyArango/connection.pyc in createDatabase(self, name, **dbArgs)
     47                 data = r.json()
     48                 if r.status_code == 201 and not data["error"] :
---> 49                         db = Database(self, name)
     50                         self.databases[name] = db
     51                         return self.databases[name]

/home/user/git/pyArango/pyArango/database.pyc in __init__(self, connection, name)
     31                 self.graphs = {}
     32 
---> 33                 self.reload()
     34 
     35         def reloadCollections(self) :

/home/user/git/pyArango/pyArango/database.pyc in reload(self)
     78         def reload(self) :
     79                 "reloads collections and graphs"
---> 80                 self.reloadCollections()
     81                 self.reloadGraphs()
     82 

/home/user/git/pyArango/pyArango/database.pyc in reloadCollections(self)
     40                         self.collections = {}
     41 
---> 42                         for colData in data["collections"] :
     43                                 colName = colData['name']
     44                                 if colData['isSystem'] :

KeyError: 'collections'

**Comment by tariqdaouda** [comment]
Are you running it on python 3? (it's not supported yet)

**Comment by tariqdaouda** [comment]
Problem solved, the last version supports V3.
