### ISSUE TITLE
Can't create connection to Arango server

### ISSUE THREAD

**Issue by warrensallen** [tariqdaouda/pyArango#18]
Arango 3 and Python 2.7 on Ubuntu (localhost).  Maybe I'm missing something, but I can't even execute your code examples without throwing this error.

```
>>> from pyArango.connection import *
>>> conn = Connection()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyArango/connection.py", line 63, in __init__
    self.reload()
  File "pyArango/connection.py", line 77, in reload
    data = r.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jitr** [comment]
I also had same issue. In my investigation I found r.status_code was 401 as I didn't passed username and password in constructor. 

I think this error code must be checked before moving ahead.

**Comment by warrensallen** [comment]
That makes sense. I turned off authentication and it is working now but in a very non-production mode.

**Comment by tariqdaouda** [comment]
Hi,

Yes in 3.0 authentication is now active by default. It means that for all the functionalities to work properly you have to either disable authentication explicitly or give it the username and password of a user that has access to _system, so it would be:

`conn = Connection(username=xxx, password=xxx)`

I am currently working on user management and when I am done you should be able to also manage user rights to different databases.

Unfortunately the server that is hosting the doc is experiencing some problems and I am unable to update it for the moment, but most of the doc is embedded in the code. If you want, you can also generate the full doc by installing sphynx along with the read the docs plugin and then typing `make clean;make html` inside the doc folder.

Cheers,

**Comment by tariqdaouda** [comment]
AikidoSession's Holder will know check for 401s for every request and print a meaningful error message. It was supposed to be part of the next version but I've just pushed it. It should get rid of these authentication surprises.

**Comment by warrensallen** [comment]
Thanks for the info @tariqdaouda and thanks for the great work.

**Comment by tariqdaouda** [comment]
No problem, thanks!
