### ISSUE TITLE
Add TTL in AQLQuery constructor

### ISSUE THREAD

**Issue by kikohs** [tariqdaouda/pyArango#19]
It seems one cannot specify the time-to-live for cursors.

I think this should do the fix.

query.py

    class AQLQuery(Query) :
        "AQL queries are attached to and instanciated by a database"
        def __init__(self, database, query, batchSize, bindVars, options, count, fullCount, ttl, rawResults = True) :
	    payload = {'query' : query, 'batchSize' : batchSize, 'bindVars' : bindVars, 'options' : options, 'count' : count, 'fullCount' : fullCount, 'ttl': ttl}

database.py

    def AQLQuery(self, query, batchSize = 100, rawResults = False, bindVars = {}, options = {}, count = False, fullCount = False, ttl=60) :
		"Set rawResults = True if you want the query to return dictionnaries instead of Document objects"
        return AQLQuery(self, query, rawResults = rawResults, batchSize = batchSize, bindVars  = bindVars, options = options, count = count, fullCount = fullCount, ttl=ttl)

**Comment by tariqdaouda** [comment]
Hi @kikohs!

Thank you for bringing that up, and for the hints. I've just pushed a modification that allows for arbitrary key word arguments to be passed for the AQL creation. You should now be able to add `ttl = 60` in the declaration.
