### ISSUE TITLE
Question on indexes

### ISSUE THREAD

**Issue by pjdvmalan** [tariqdaouda/pyArango#2]
Hi,

How is Arango indexes handled using this package - ie. how would I create an index?

**Comment by tariqdaouda** [comment]
Hi,

Sorry I've just noticed the issue. PyArango is mainly aimed to help developers develop as fast as possible and reliably as possible. For that reason much effort as been devoted to the validation and interface. As indexes are more about database administration they are currently not supported, but  they are the next thing to be implemented.

Cheers,
