### ISSUE TITLE
add travis-ci

### ISSUE THREAD

**Issue by brennv** [tariqdaouda/pyArango#23]
Add [travis-ci](https://docs.travis-ci.com/) so we can watch our PRs pass or fail across multiple Python environments.

**Comment by brennv** [comment]
Started troubleshooting arangodb as a dockerized service:
https://github.com/brennv/pyArango/tree/add-travis-ci

**Comment by brennv** [comment]
travis is working but it looks like we'll need to merge @dotthebart's https://github.com/tariqdaouda/pyArango/pull/22 before even the python2 tests will pass

**Comment by tariqdaouda** [comment]
Is it working now? The current version on [python3](https://github.com/tariqdaouda/pyArango/tree/python3) should run on python 3.4 and above. It's not compatible yet with python 2.7.

**Comment by brennv** [comment]
Its working :) https://travis-ci.org/tariqdaouda/pyArango/pull_requests
