### ISSUE TITLE
simplify tests

### ISSUE THREAD

**Issue by brennv** [tariqdaouda/pyArango#25]
Simplify tests.py so we can run all tests in tests/ like with:
`python -m unittest discover tests/`

Currently errors out on globals. Also replacing rawinput methods with os.getenv so it plays well with automated test environments.

**Comment by tariqdaouda** [comment]
Good idea, I've mixed the two approaches. It will first check the environment variables before asking for the username/password. That way it can be easily automated and also easily ran by anyone.

**Comment by brennv** [comment]
Cool, I remixed the two approaches so it works for travis https://github.com/tariqdaouda/pyArango/pull/30

**Comment by tariqdaouda** [comment]
Cool!
