### ISSUE TITLE
Inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by mark-eastwood** [tariqdaouda/pyArango#3]
I needed to remove multiple instances of spaces mixed in with tabs in the indentation to get the code to run. Also, setup.py did not complete properly because of this error. If you're not writing this code in notepad, you will likely find a feature in your IDE along the lines of "replace tabs with spaces". Please just use it, just makes life easier for everyone.

I am using pyArango-1.0.1

**Comment by tariqdaouda** [comment]
Well, If it can ease your mind I use sublime text, and I suggest you try it if you haven't done so already, it's awesome.
I have been using the latest version pyArango available on github for the whole day and I haven't noticed anything. I even did a python setup.py develop when I read this issue, and everything went fine. So please could you give more infos about this peculiar error you are reporting.

**Comment by mark-eastwood** [comment]
Hi thanks for replying. I was actually presuming this code could run using Python 3, since I did not see otherwise. If you have no intention of supporting Python 3, you should probably just close this issue. Could you please update the git page to clearly state that you are not supporting Python 3? as it was only after reviewing the code that I realized this.

As of Python 3 you cannot mix tabs and spaces, so if you plan to move over eventually, might as well get into the habit of choosing one or the other (spaces being the clear choice).

**Comment by tariqdaouda** [comment]
Done, I work in a context where switching to Python 3 is not necessarily the soundest of choices therefor, I am not planning to move any of my packages to Python 3 any time soon. If you would like to port pyArango to Python 3 please feel free to do so.
