### ISSUE TITLE
Support for the Export API

### ISSUE THREAD

**Issue by kikohs** [tariqdaouda/pyArango#43]
ArangoDB has a special very fast API to export a full collection. It would be great to have it in the driver, the benchmarks are impressive:

https://jsteemann.github.io/blog/2015/04/04/more-efficient-data-exports/

Roughly it is equivalent to:

```
curl
  -X POST
  http://localhost:8529/_api/export?collection=users
--data '{"batchSize":5000}'

```

With a cursor

More info:
https://docs.arangodb.com/cookbook/UseCases/ExportingData.html

**Comment by tariqdaouda** [comment]
Ok, I'll have a look into that when I have a bit more time!

**Comment by tariqdaouda** [comment]
functionality added by @meatb4all
