### ISSUE TITLE
pyArango very slow on windows

### ISSUE THREAD

**Issue by cheve1969** [tariqdaouda/pyArango#44]
I tested pyArango 1.2.5 in python 3.5 on windows and linux. Arangodb 3 running local in every system.
On linux connection time is 0.04 seconds. A simple query took 0.0089 seconds.

On windows I got 3 seconds and the simpe query took  1 second.

My windows machine is newer and faster than my linux machine.

**Comment by tariqdaouda** [comment]
Are you sure this is related to pyArango? How fast are the queries submitted through the graphical interface?

**Comment by cheve1969** [comment]
Through the arango web ui is very fast: less than 0.001 seconds.
I checked that using pyArango on windows, every call to the server is taking at least 1 second.
The next three lines took 3.2 seconds:

conn = Connection(username="username", password="password")
db = conn["database"]
col = db["col"]

The same on linux took no more than 0.04 seconds.

**Comment by tariqdaouda** [comment]
This seems to be related to the way windows handles connections. Maybe @dothebart could have an idea about what's going on.

**Comment by MrPieces** [comment]
We checked on our side and didn´t find any ticket mentioning this kind of behaviour. 

Would you mind testing your query and it´s performance with e.g. NodeJS. It seems a bit strange that the query works that fast under Linux but that slow under Windows. Seems more like a Windows issue than a driver issue. 

Would be great to get your feedback on the results!

**Comment by cheve1969** [comment]
I tested with NodeJS 6.2 on windows and is fast.
The slowest part is the first connection that took 90 ms.
Most queries 1 to 3 ms.

With python 3.5 every call to the server take at least 1 second.

**Comment by tariqdaouda** [comment]
What about python 2.7?

**Comment by MrPieces** [comment]
@cheve1969 We at ArangoDB would like to investigate a bit deeper because this is a really uncommon behaviour! Would you mind sharing some infos about your exact setup (Windows version etc.) and  your test program if possible. We´d like to replicate your issue and thereby understand what happens.

You can reach me at jan.stuecke at arangodb.com

**Comment by cheve1969** [comment]
Tested with python 2.7 and performance is similar to python 3.5.

**Comment by cheve1969** [comment]
My setup: 
Windows 7 sp1, Intel core i7 2.7GHz 8GB ram
Arango 3.0.2
Python 2.7.10 and 3.5.1 64bit

The code is very simple and the collection has only 3 documents.

```
import time
from pyArango.connection import Connection

t1 = time.clock()

conn = Connection(username="username", password="password")
db = conn["database"]
people = db["people"]


t2 = time.clock()

data = people.fetchAll()
#aql = "for c in people return c"
#data = db.AQLQuery(aql)

t3 = time.clock()

for i in data:
    print(i._id, i["name"])

t4 = time.clock()
data = people.fetchAll()
t5 = time.clock()

print("Connection time", t2-t1)
print("Fetch time", t3-t2)
print("For time", t4-t3)
print("TOTAL", t4-t1)
print("Fetch time 2", t5-t4)
```

**Comment by mpv1989** [comment]
tested your code. When I write the ip in param "arangoURL", it is fast on Windows too.
Can you please test it on your machine?

`conn = Connection(arangoURL="http://127.0.0.1:8529", username="username", password="password")`

**Comment by cheve1969** [comment]
@mpv1989 Wow... that solves the problem.
The connection is 0.06 seconds now and the query is 0.01 seconds.
Thanks.

**Comment by tariqdaouda** [comment]
Wow... Thanks @mpv1989! I have modified the source to have the ip in the default URL.
