### ISSUE TITLE
DocumentCache __getitem__ BUG ?

### ISSUE THREAD

**Issue by crane-may** [tariqdaouda/pyArango#45]
In pyArango/collection.py#L85
```python
def __getitem__(self, key) :
        if key in self.cacheStore :
            try :
....
```

I think the if statement is unnecessary, and it causes an error in `Collection. __getitem__`.

**Comment by crane-may** [comment]
I have try to remove if statement, then met more issues:

- Document.key or Document._key
- DocumentCache.cache is return CachedDoc, not Document

I think cache feature is not finish, isn't it?

**Comment by tariqdaouda** [comment]
You're right there seem to be a problem with cache. it should be document._key, I have fixed It. Thanks for letting me know.

**Comment by tariqdaouda** [comment]
I have updated the cache to expose document transparently. It should make the interface easier to use, you should be able to use a CachedDoc as a normal doc.
