### ISSUE TITLE
Documentation is not clear ....for me

### ISSUE THREAD

**Issue by AndreiD** [tariqdaouda/pyArango#51]
Greetings, sorry for asking a newbie question but for

myDocument.getInEdges(myConnections)
myConnections.getInEdges(myDocument)

how exactly I get an object "myDocument" 

If I import the from pyArango.collection import Document
I don't see any functions for getting a document by id for example, only how to create one.

My question is:

I have x documents. I want to get the edges from one of them. I know it's id/key.
I want it as easy as possible.

one option would be
# FOR v, e, p IN 1 OUTBOUND 'collection_name/id' GRAPH 'graphname'
#     RETURN  xyz

is there a better/simpler way to get edges for a document

**Comment by tariqdaouda** [comment]
Here's a more detailed doc for

- [Documents](http://bioinfo.iric.ca/~daoudat/pyArango/document.html#)
- [Collections](http://bioinfo.iric.ca/~daoudat/pyArango/collection.html#pyArango.collection.Edges.getEdges.)

It would be either:
`myDocument.getOutEdges(edges)`
Where edges is a collection of edges
or:
`myConnections.getInEdges(myDocument)
`
Where my doecument is either a document or an _id string
