### ISSUE TITLE
No Documented way to actually get a graph

### ISSUE THREAD

**Issue by Slater-Victoroff** [tariqdaouda/pyArango#57]
Docs show the ability to create a graph, but trying to access it does not currently seem possible outside of the first session when it's created.

Collections are accessible via the bracket syntax, but graphs are not. There's no obvious method for doing this either.

**Comment by tariqdaouda** [comment]
Graphs are accessible using the bracket syntax just like collection by through the *.graphs* dictionary of a **Database** object: `database.graphs[<graph_name>]`
