### ISSUE TITLE
UNSET action for Document

### ISSUE THREAD

**Issue by AxelRHD** [tariqdaouda/pyArango#59]
Very great tool for Arango. But I am missing the opportunity to unset an attribute of a document-object. Would be great to implement it.

**Comment by tariqdaouda** [comment]
Thank you @AxelRHD. Can you be just bit more specific, what do you mean by unsetting an attribute?

**Comment by AxelRHD** [comment]
I am very new to ArangoDB and now I see that I misunderstood the unsetting-functionality. It is to suppress attributes in the return-statement of an AQL-Query. I am just trying to figure out, what is the best way to drop/delete an attribute from an existing document object (e. g. drop the name represented by doc['name']). Maybe I've missed something? Anyway... you can close this issue and thanks for the very fast response.

**Comment by tariqdaouda** [comment]
No problem, you can do: del doc["name"] followed by doc.save(). That should work.
