### ISSUE TITLE
mustn't decode empty download

### ISSUE THREAD

**Issue by dothebart** [tariqdaouda/pyArango#70]
In `connection.py` the method  `r.json` will assert if there is no reply content (as i.e. if the HTTP returncode is 401) 

Most probably a change like that could make it run smoother:

```
    def reload(self) :
...
        data = [];
        if r.content.length > 0:
            data = r.json()
        else if r.status_code == 401:
            data["errorMessage"] = "Unauthorized"
```

Else the user will just get an exception like that:

```
  File "/usr/local/lib/python2.7/dist-packages/pyArango/connection.py", line 102, in __init__
    self.reload()
  File "/usr/local/lib/python2.7/dist-packages/pyArango/connection.py", line 121, in reload
    data = r.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 894, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
```

which won't give much information on the original error.

**Comment by tariqdaouda** [comment]
I agree. I can't update it right now. Could you make me a pull request? I prefer not to modify the code on github.

**Comment by dothebart** [comment]
ok, need to fuzz with my workingcopy.

**Comment by anuragasaurus** [comment]
wouldn't we need to implement this thing in every http call everywhere?

**Comment by tariqdaouda** [comment]
Yes. There is a check performed here [connection line 41](https://github.com/tariqdaouda/pyArango/blob/master/pyArango/connection.py#L41) for every connection. It could be inserted there.

**Comment by dothebart** [comment]
ok, so this pr is probably not the complete solution then.

**Comment by tariqdaouda** [comment]
Fixed it.
