### ISSUE TITLE
exists() not implemented

### ISSUE THREAD

**Issue by sunsided** [tariqdaouda/pyArango#77]
It appears no `exists` method ... exists ... on the `Collection` class. Can we add that?

When I try to get a non-existing document using `fetchDocument`, the code fails (as expected) with a `KeyError`. So I tried using `'doc_key' in collection`, but since `Collection` doesn't implement `__contains__` either, this results in the same error.

**Comment by tariqdaouda** [comment]
Ok i'll add it.
