### ISSUE TITLE
Unable to create user-defined "_key"

### ISSUE THREAD

**Issue by palooney** [tariqdaouda/pyArango#80]
Hello, I have a JSON  sample like 
```{json}
sample = [{
        "_key": "xxxxxxxxx", 
        "body_len": 4, 
        "date": "Mon, 14 May 2001 16", 
        "mid": "18782981.1075855378110", 
        "subject": "", 
        "type": "receiver"
    },
 ...
...
]
```

But when I save the document into Arango, the ```_key``` did not get passed, but all other attributes got passed, and ```_key``` in the Arango shown as random-generated numbers.

My Python codes are listed below:

```{python}
from pyArango.connection import *
from pyArango.collection import *
import json

conn = Connection(username = "root", password = "")
db = conn["test_db"]
coll = db.createCollection(name = "test")
for each in s:
    coll.createDocument(each).save()
```

I still don't know what happened. Any help will be thankful!

**Comment by tariqdaouda** [comment]
Hi @palooney,

"_key" is bit special. Could you try to explicitly set it doc: ["_key_"] = xxxx ?

**Comment by palooney** [comment]
Hello @tariqdaouda, thanks for your reply. It could fix it, but it would be problematic if I want to create edge using ```from``` and ```to``` instead of ```_from``` and ```_to```. Do you have any suggestion?

**Comment by tariqdaouda** [comment]
Hi @palooney ,

I've just pushed a modification that should allow you to setup __key_ or any other private like the rest of the fields.
You can of course use _from_ or _to_ instead of __from_ and __to_, but you wont be able to use any of the graph/edges functionalities that Arangodb provides.

Cheers,
