### ISSUE TITLE
Delete db functionality

### ISSUE THREAD

**Issue by LukeMathWalker** [tariqdaouda/pyArango#84]
At the moment it is not possible, using pyArango, to actually drop an ArangoDB database.
Is there a specific reason for this?

I have written a script to successfully **_clean_** a database (drop all graphs and collections) using pyArango functionalities, but it doesn't really solve the issue.
By the way I could draft a pull request to integrate this last functionality into the database class (a `drop_all_collections` method?)

**Comment by LukeMathWalker** [comment]
@tariqdaouda

**Comment by tariqdaouda** [comment]
Hi @LukeMathWalker ,

No there's no specific reason for it missing. It would be great if you could send me a pull request. Just make sure that the tests are not broken and will take care of making sure it is well inregrated.

Cheers,

**Comment by LukeMathWalker** [comment]
Hi @tariqdaouda, I just sent a pull request to add a `dropAllCollections` method to the database class.  #86 
I'll try to work on the deleteDatabase method during the week.

Bests

**Comment by intcitium** [comment]
Has the delete database method ever been implemented?

**Comment by arkanmgerges** [comment]
Hi is there any delete database, that is implemented?

**Comment by arkanmgerges** [comment]
I was reading the code, for now in order to delete the database I did:
`
connection = Connection(
            arangoURL='localhost',
            username='userdb',
            password='pass1234'
        )
url = connection.getURL() + "/database/" + dbName
  connection.session.delete(url)`
