### ISSUE TITLE
Query result dictionary order lost

### ISSUE THREAD

**Issue by aishusreeni** [tariqdaouda/pyArango#85]
```
aql = """FOR x IN Link
              FILTER CONTAINS(x._from, "Core")
              SORT x._from, x._to, x.Port1
              RETURN {[x._from]:x.Port1, [x._to]:x.Port2}"""
result = self.aql_query(aql)
print(result.result[0])
```

 ```
def aql_query(self, aql, rawResults=True, batchSize=100):
   query_result = self.db.AQLQuery(aql, rawResults=rawResults, batchSize=batchSize)
   return query_result

```
Link is a collection of edges in a topology. 
Example of a document in Link:{"Port1":"Port2","Port2":"NM_Port1","_from":"Router/Core1","_to":"Router/Edge2","name":"Core1Edge2"}

Expected response while running pyArango code:
[{'Router/Core1': 'Port1', 'Router/Edge1': 'NM_Port1'}, {'Router/Core1': 'Port2', 'Router/Edge2': 'NM_Port1'}]

Received response while running pyArango code:
[{'Router/Edge1': 'NM_Port1', 'Router/Core1': 'Port1'}, {'Router/Edge2': 'NM_Port1', 'Router/Core1': 'Port2'}]

Expected and received response while running the query in the arango interface:
[{'Router/Core1': 'Port1', 'Router/Edge1': 'NM_Port1'}, {'Router/Core1': 'Port2', 'Router/Edge2': 'NM_Port1'}]

My understanding is - when python gets the query result, it does not care about the order in which the dictionaries are in the result. So even thought the sort function is present in the arango query, it is being overwritten. 

I wonder if something can be done about this issue!

**Comment by tariqdaouda** [comment]
Hi @aishusreeni,

The results are normally stored in lists so the order should be the same.
@dothebart do you have an idea of what's going on?

**Comment by dothebart** [comment]
Hi, 
Quoting http://json.org/  :
 `An object is an unordered set of name/value pairs. An object begins with { (left brace) and ends with } (right brace). Each name is followed by : (colon) and the name/value pairs are separated by , (comma).`

So you basically can't lean on the sequence of attributes in a json document; you can only sort lists. 

Compared this with: 
https://stackoverflow.com/questions/10844064/items-in-json-object-are-out-of-order-using-json-dumps
it seems that python supports sorting objects if you explicitely make it to.

You usually should lean on access by the key to object attributes, not by their sequence.
