### ISSUE TITLE
Modifying validation schema for an already existing Collection

### ISSUE THREAD

**Issue by Jacobgoss30** [tariqdaouda/pyArango#88]
Hello!

I have a Collection in my database which was defined using a certain combination of validators.
I realized I made a mistake and I changed my validation schema, but pyArango does not seem to pick up the changes automatically (and I don't want to delete and reinstante the db either).

Is there a function to force him to acknowledge the new structure?

**Comment by tariqdaouda** [comment]
Hi @Jacobgoss30,

As ArangoDB has no schema validation capabilities, the schema validation is entirely on pyArango's side and ArangoDB is unaware of it.That means that you can usually change it as much as you want without having to worry about the DB. If you had no errors if probably means that everything is running just fine.

The only problems arise when you add in new validation schemes that are not compatible with data already in the DB ex: add a "Not Null". In that case you can solve the problem by adding defaults that fit the validation rules.

**Comment by Jacobgoss30** [comment]
Ok!
Thanks for the explanation :)
