### ISSUE TITLE
client api shouldn't be changed this way

### ISSUE THREAD

**Issue by Codealist** [tariqdaouda/pyArango#89]
You have interesting feature in master branch (using statsd to handle statistics).
However when i installed a master branch distribution i met error with Collection::createDocument() method
You changed high-level api without any deprecation warnings in 1.3.0
Since I have cases when i create documents from a post messages with prepopulated data i had to change all my client code from createDocument() to createDocument_() which is (honestly) a bit weird.

https://github.com/tariqdaouda/pyArango/compare/1.3.0...master#diff-b710a95686ae3f74d5df8a2cf52930a8R295

**Comment by tariqdaouda** [comment]
You're right. This change was intended for the dev branch and should not have found its way into the master. It is fixed, thanks for the heads up.

**Comment by Codealist** [comment]
brilliant!
Probably you know it, however if you don't mind i'd recommend doing something like this in future occasions:
```
def old_way_proc():
    import warnings
    warnings.warn("a function module.old_way_proc is deprecated in 1.3.2, and will be removed in 1.4.0."
                  "Use module.new_way_proc instead", DeprecationWarning)
    # doing some stuff
```
`

**Comment by tariqdaouda** [comment]
Thanks, I'll keep that in mind for future releases.
