### ISSUE TITLE
Cannot bulk save from a list of dictionaries: getStore Attribute is not defined

### ISSUE THREAD

**Issue by maxpareschi** [tariqdaouda/pyArango#99]
https://github.com/tariqdaouda/pyArango/blob/2aaa7e8626da1991001ccbf1c4745f1440c1a734/pyArango/collection.py#L487

This line is the culprit. There's no getStore() in python's dictionary object.

Maybe I'm missing something and getStore() is implemented somewhere in pyArango, but i still cannot find it.

Also, method works if I use the documentation version (displayed after clicking on source, [link](http://bioinfo.iric.ca/~daoudat/pyArango/_modules/pyArango/collection.html#Collection.bulkSave)).

Corrected line would be as follows:
`payload.append(json.dumps(d))`

**Comment by tariqdaouda** [comment]
Hi, yes getStore() only works for pyArango objects. I can add support for dicts.

**Comment by maxpareschi** [comment]
Ah i was sure i could do it with plain dicts as stated in the docs.
I'm fetching csvs, converting them to dicts and storing them in a list.
Those would be my documents, Does it mean i need to convert my dicts into pyArango document Objects in my readCSV method?
Thanks

**Comment by tariqdaouda** [comment]
I just pushed support for dicts. You can try it.

**Comment by maxpareschi** [comment]
Thanks.
Tried it, and while it does recognize dicts in a list now it still seems to need a json.dumps on said dict to join to the payload correctly.
That's my teminal error.

> Traceback (most recent call last):
>   File "make_db.py", line 57, in <module>
>     mario_users.bulkSave(kk)
>   File "c:\dev\projects\mario-core\lib\pyarango\pyArango\collection.py", line 492, in bulkSave
>     payload = '\n'.join(payload)
> TypeError: sequence item 0: expected str instance, dict found

`payload.append(json.dumps(d))` should work unless there's something else that i'm missing

**Comment by tariqdaouda** [comment]
Should be fixed now. Sorry about that.
